### ISSUE TITLE
Add an autoformatter

### ISSUE THREAD

**Issue by TheButlah** [esp-rs/esp-println#24]
I tried to create a PR and had a lot of trouble, because the code isn't formatted with `rustfmt`. I therefore needed to manually go through and delete everything that got formatted, so that I didn't submit a bunch of formatting noise and risk getting my PR rejected.

Would it be ok to add a `rustfmt.toml` file to the repo to indicate that the use of an autoformatter is permissible in PRs and define the format?

**Comment by bjoernQ** [comment]
With the default formatter settings, I get _some_ changes in the macros, true. I'm wondering if you experienced more changes?

Anyway - sure - makes sense to add a `rustfmt.toml` - ideally this one https://github.com/esp-rs/esp-hal/blob/main/rustfmt.toml
