### ISSUE TITLE
Crates.io release?

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-println#3]
Anything blocking us from atleast a 0.1 release?

**Comment by bjoernQ** [comment]
I don't see anything to be honest

@jessebraham what do you think?

**Comment by jessebraham** [comment]
I just opened #4 which I think we should merge first, but yeah other than that there's no reason we can't publish an initial release.

**Comment by bjoernQ** [comment]
Great! I can publish it on Monday or any team member can do it before, if we want this be done soon

**Comment by jessebraham** [comment]
The first release has been published on crates.io:  
https://crates.io/crates/esp-println

**Comment by bjoernQ** [comment]
Thanks - I totally forgot about it 😊
