### ISSUE TITLE
docs.rs build has failed

### ISSUE THREAD

**Issue by elpiel** [esp-rs/esp-println#33]
All the docs.rs builds fail since the beginning.
Here're the logs for the last one in September and it failed:

https://docs.rs/crate/esp-println/0.3.1/builds/633020

**Comment by elpiel** [comment]
This continues to be an issue:
https://docs.rs/crate/esp-println/0.5.0/builds/795172

**Comment by bjoernQ** [comment]
I guess we can close this - we have proper docs since 0.6.0
