### ISSUE TITLE
Issues on ESP32-S3 and either serial_jtag or uart

### ISSUE THREAD

**Issue by bugadani** [esp-rs/esp-println#53]
If using the builtin USB-JTAG interface, esp-println tends to misbehave differently under different circumstances. The issues are most visible using `defmt` but I'm not sure if this issue is defmt-specific:

 - with `uart` a simple defmt demo stops working after a few seconds
 - with `uart` a real-world application works, but can lag if the same output is printed multiple times
 - with `serial_jtag` the simple demo works exactly as expected
 - with `serial_jtag` the real-world application sometimes outputs defmt frames that espflash can't parse.

That one feature works in one application, the other in another, but they won't work when switched around is weird.

Reproduction: https://github.com/bugadani/esp32s3-defmt-example (current state is working as expected, switching to `uart` does not.)

I experience my issues on Windows 11 which may or may not affect it

**Comment by bjoernQ** [comment]
Maybe worth to try it with a different generic serial-monitor 🤔 just to rule out the problem really isn't on the host side

**Comment by bugadani** [comment]
And probably a different OS to see if it's not the drivers either :) Good point!

**Comment by bjoernQ** [comment]
ah I remember that thing about jtag_serial  ... initially we didn't drop data but the problem was then when the device wasn't attached to a host it blocked forever

**Comment by bugadani** [comment]
> it blocked forever

oh that explains [probably not so public info] 🙃

**Comment by bugadani** [comment]
Well, my problems went away, let's hope I didn't introduce new ones for the other SoC lines 😅
