### ISSUE TITLE
Document features 

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/esp-println#67]
We should document the available features in the readme. Also we should note conflicts with default features. eg: If you enable `rtt`, defatuls-features must be false, otherwise there will be a conflict with `uart`

**Comment by jessebraham** [comment]
Please also add them to the module documentation in `lib.rs` so that they're documented on `docs.rs` as well.

(Looks like we don't even have a top-level doc comment in there, yet 😅 )
